services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recruitment-backend
    ports:
      - "8000:8000"
    environment:
      - ZHIPU_API_KEY=${ZHIPU_API_KEY:-your_zhipu_api_key_here}
      - USE_MOCK_AI=${USE_MOCK_AI:-false}
      - DEBUG=False
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/recruitment_assistant.db:/app/recruitment_assistant.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - recruitment-network
    develop:
      watch:
        # 同步源代码变更到容器内，触发应用自动重载（若进程支持）
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - "**/__pycache__/**"
            - "**/*.pyc"
            - "**/.venv/**"
            - "**/.mypy_cache/**"
            - "**/.pytest_cache/**"
            - "**/uploads/**"
        # 依赖文件变化时重建镜像
        - path: ./backend/requirements.txt
          action: rebuild

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recruitment-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - recruitment-network
    develop:
      watch:
        # 源码或配置变化时重建前端镜像（打包产物由nginx直接提供）
        - path: ./frontend/src
          action: rebuild
        - path: ./frontend/public
          action: rebuild
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend/vite.config.*
          action: rebuild

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: recruitment-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - recruitment-network

networks:
  recruitment-network:
    driver: bridge

volumes:
  uploads:
  database:
