version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recruitment-backend
    ports:
      - "8000:8000"
    environment:
      - ZHIPU_API_KEY=${ZHIPU_API_KEY:-your_zhipu_api_key_here}
      - USE_MOCK_AI=${USE_MOCK_AI:-false}
      - DEBUG=False
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/recruitment_assistant.db:/app/recruitment_assistant.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - recruitment-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recruitment-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - recruitment-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: recruitment-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - recruitment-network

networks:
  recruitment-network:
    driver: bridge

volumes:
  uploads:
  database:
